# Generated by Django 4.1.2 on 2022-10-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0002_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(choices=[('48', '48'), ('47', '47'), ('49', '49'), ('50', '50')], max_length=5),
        ),
    ]
