# Generated by Django 4.1.2 on 2022-10-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0003_alter_student_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
