# Generated by Django 4.1.2 on 2022-10-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0004_alter_student_email_alter_teacher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='short_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
