# Generated by Django 4.1.2 on 2022-10-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0007_examcommittee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamCommittee',
        ),
    ]
