# Generated by Django 4.1.2 on 2022-10-22 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0008_delete_examcommittee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_chairman', models.CharField(max_length=100, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvApp.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
