# Generated by Django 4.1.2 on 2022-10-22 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0010_alter_examcommittee_is_chairman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcommittee',
            name='is_chairman',
            field=models.CharField(choices=[{'NS', 'NafisSarker-( NS )'}, {'AJ', 'AjoySarker-( AJ )'}], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examcommittee',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvApp.teacher'),
        ),
    ]
