# Generated by Django 4.1.1 on 2022-10-26 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0011_alter_examcommittee_is_chairman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcommittee',
            name='is_chairman',
            field=models.CharField(choices=[{'NS', 'NafisSarker-( NS )'}, {'AJ', 'AjoySarker-( AJ )'}, {'SakibMollah-( SM )', 'SM'}, {'bijoySarker-( BS )', 'BS'}], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.PositiveIntegerField()),
                ('examcommittee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvApp.examcommittee')),
            ],
        ),
    ]
