# Generated by Django 4.1.1 on 2022-10-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0013_invigilatordb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcommittee',
            name='is_chairman',
            field=models.CharField(choices=[('Yes', 'Chairman'), ('No', 'Just a Teacher')], max_length=100, null=True),
        ),
    ]
