# Generated by Django 4.1.1 on 2022-10-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0014_alter_examcommittee_is_chairman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examcommittee',
            name='is_chairman',
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_chairman',
            field=models.CharField(choices=[('Yes', 'Chairman'), ('No', 'Just a Teacher')], max_length=100, null=True),
        ),
    ]
