# Generated by Django 4.1.1 on 2022-10-26 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0015_remove_examcommittee_is_chairman_teacher_is_chairman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='examcommittee',
        ),
        migrations.AddField(
            model_name='examcommittee',
            name='semester',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='InvApp.semester'),
        ),
        migrations.AddField(
            model_name='semester',
            name='semId',
            field=models.IntegerField(null=True),
        ),
    ]
