# Generated by Django 4.1.1 on 2022-10-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0017_remove_examcommittee_teacher_examcommittee_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcommittee',
            name='teacher',
            field=models.ManyToManyField(null=True, to='InvApp.teacher'),
        ),
    ]
