# Generated by Django 4.1.1 on 2023-03-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0020_remove_teacher_email_remove_teacher_pwd_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='chariman',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='InvApp.teacher'),
        ),
    ]
