# Generated by Django 4.1.1 on 2023-03-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0021_semester_chariman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='chariman',
            new_name='chairman',
        ),
    ]
