# Generated by Django 4.1.1 on 2023-03-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0022_rename_chariman_semester_chairman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_chairman',
        ),
    ]
