# Generated by Django 4.1.2 on 2023-03-21 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0023_remove_teacher_is_chairman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='InvApp.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InvApp.course'),
        ),
    ]
