# Generated by Django 4.1.2 on 2023-03-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0024_course_semester_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='courses',
        ),
        migrations.AddField(
            model_name='semester',
            name='courses',
            field=models.ManyToManyField(null=True, to='InvApp.course'),
        ),
    ]
