# Generated by Django 4.1.2 on 2023-03-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0025_remove_semester_courses_semester_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('teachers', models.ManyToManyField(null=True, to='InvApp.teacher')),
            ],
        ),
    ]
