# Generated by Django 4.1.2 on 2023-03-22 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0026_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='routine',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='InvApp.routine'),
        ),
    ]
