# Generated by Django 4.1.2 on 2023-03-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0028_rename_routine_semester_final_routine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='semsester',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
