# Generated by Django 4.1.2 on 2023-03-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0029_routine_semsester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='semsester_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
