# Generated by Django 4.1.2 on 2023-03-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0030_semester_semsester_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='semsester_name',
            new_name='semester_name',
        ),
    ]
