# Generated by Django 4.1.1 on 2023-03-22 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0031_rename_semsester_name_semester_semester_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='semId',
        ),
    ]
