# Generated by Django 4.1.1 on 2023-03-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0041_notice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
