# Generated by Django 4.1.1 on 2023-03-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0042_notice_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_id',
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(blank=True, choices=[('48', '48'), ('47', '47'), ('49', '49'), ('50', '50'), ('51', '51')], default='48', max_length=30, null=True),
        ),
    ]
