# Generated by Django 4.1.1 on 2023-03-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0043_remove_teacher_teacher_id_alter_student_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
    ]
