# Generated by Django 4.1.1 on 2023-03-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0044_student_image_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_time',
            field=models.TimeField(null=True),
        ),
    ]
