# Generated by Django 4.1.1 on 2023-04-04 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0047_remove_invigilatordb_semester_delete_examcommittee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='final_routine',
        ),
        migrations.AlterField(
            model_name='routine',
            name='semsester',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='InvApp.semester'),
        ),
    ]
