# Generated by Django 4.1.1 on 2023-04-04 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0048_remove_semester_final_routine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='semsester',
            new_name='semester',
        ),
    ]
